config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get 'customerrequests/index'

  get 'customerrequests/show'

  resources :customers
  resources :sproviders
  
  get '/cooks' => 'cooks#index'
  get 'cooks/:spid' => 'cooks#cookrequest'
  get 'cooks/index'

  get 'cooks/show'

  get 'dataviews/new' => 'dataviews#new'
  devise_scope :user do    
  match '/sessions/user', to: 'devise/sessions#create', via: :post
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'customerrequests/:customer_id' => 'customerrequests#userrequest'
  resources :customerrequests
  resources :dataviews
  resources :cooks
  resources :negative_feedbacks
  root 'dataviews#index'

end

app/models/negative_feedback.rb
class NegativeFeedback < ActiveRecord::Base
end

app/controllers/negative_feedbacks_controller.rb
class NegativeFeedbacksController < ApplicationController
  before_action :set_negative_feedback, only: [:show, :edit, :update, :destroy]

  # GET /negative_feedbacks
  # GET /negative_feedbacks.json
  def index
    @negative_feedbacks = NegativeFeedback.all
  end

  # GET /negative_feedbacks/1
  # GET /negative_feedbacks/1.json
  def show
  end

  # GET /negative_feedbacks/new
  def new
    @negative_feedback = NegativeFeedback.new
  end

  # GET /negative_feedbacks/1/edit
  def edit
  end

  # POST /negative_feedbacks
  # POST /negative_feedbacks.json
  def create
    @negative_feedback = NegativeFeedback.new(negative_feedback_params)

    respond_to do |format|
      if @negative_feedback.save
        format.html { redirect_to @negative_feedback, notice: 'Negative feedback was successfully created.' }
        format.json { render :show, status: :created, location: @negative_feedback }
      else
        format.html { render :new }
        format.json { render json: @negative_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /negative_feedbacks/1
  # PATCH/PUT /negative_feedbacks/1.json
  def update
    respond_to do |format|
      if @negative_feedback.update(negative_feedback_params)
        format.html { redirect_to @negative_feedback, notice: 'Negative feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @negative_feedback }
      else
        format.html { render :edit }
        format.json { render json: @negative_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /negative_feedbacks/1
  # DELETE /negative_feedbacks/1.json
  def destroy
    @negative_feedback.destroy
    respond_to do |format|
      format.html { redirect_to negative_feedbacks_url, notice: 'Negative feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negative_feedback
      @negative_feedback = NegativeFeedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def negative_feedback_params
      params.require(:negative_feedback).permit(:date, :cook, :customer, :feedback, :remark, :spid, :customer_id)
    end
end

app/helpers/negative_feedbacks_helper.rb
module NegativeFeedbacksHelper
end

app/views/negative_feedbacks/_form.html.erb
<%= form_for(@negative_feedback) do |f| %>
  <% if @negative_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@negative_feedback.errors.count, "error") %> prohibited this negative_feedback from being saved:</h2>

      <ul>
      <% @negative_feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :cook %><br>
    <%= f.collection_select :cook, Sprovider.all, :id, :uname %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.collection_select :customer, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :feedback %><br>
    <%= f.text_area :feedback %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_area :remark %>
  </div>
  <div class="field">
    <%= f.label :spid %><br>
    <%= f.collection_select :spid, Sprovider.all, :uname, :id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :name, :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/negative_feedbacks/edit.html.erb
<h1>Editing Negative Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @negative_feedback %> |
<%= link_to 'Back', negative_feedbacks_path %>

app/views/negative_feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Negative Feedbacks</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Cook</th>
      <th>Customer</th>
      <th>Feedback</th>
      <th>Remark</th>
      <th>Spid</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @negative_feedbacks.each do |negative_feedback| %>
      <tr>
        <td><%= negative_feedback.date %></td>
        <td><%= negative_feedback.cook %></td>
        <td><%= negative_feedback.customer %></td>
        <td><%= negative_feedback.feedback %></td>
        <td><%= negative_feedback.remark %></td>
        <td><%= negative_feedback.spid %></td>
        <td><%= negative_feedback.customer_id %></td>
        <td><%= link_to 'Show', negative_feedback %></td>
        <td><%= link_to 'Edit', edit_negative_feedback_path(negative_feedback) %></td>
        <td><%= link_to 'Destroy', negative_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Negative feedback', new_negative_feedback_path %>

app/views/negative_feedbacks/new.html.erb
<h1>New Negative Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', negative_feedbacks_path %>

app/views/negative_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @negative_feedback.date %>
</p>

<p>
  <strong>Cook:</strong>
  <%= @negative_feedback.cook %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @negative_feedback.customer %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @negative_feedback.feedback %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @negative_feedback.remark %>
</p>

<p>
  <strong>Spid:</strong>
  <%= @negative_feedback.spid %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @negative_feedback.customer_id %>
</p>

<%= link_to 'Edit', edit_negative_feedback_path(@negative_feedback) %> |
<%= link_to 'Back', negative_feedbacks_path %>