config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get 'customerrequests/index'

  get 'customerrequests/show'

  resources :customers
  resources :sproviders
  
  get '/cooks' => 'cooks#index'
  get 'cooks/:spid' => 'cooks#cookrequest'
  get 'cooks/index'

  get 'cooks/show'

  get 'dataviews/new' => 'dataviews#new'
  devise_scope :user do    
  match '/sessions/user', to: 'devise/sessions#create', via: :post
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'customerrequests/:customer_id' => 'customerrequests#userrequest'
  resources :customerrequests
  resources :dataviews
  resources :cooks
  resources :negative_feedbacks
  root 'dataviews#index'

end

app/models/sprovider.rb
class Sprovider < ActiveRecord::Base
end

app/controllers/sproviders_controller.rb
class SprovidersController < ApplicationController
  before_action :set_sprovider, only: [:show, :edit, :update, :destroy]

  # GET /sproviders
  # GET /sproviders.json
  def index
    @sproviders = Sprovider.all
  end

  # GET /sproviders/1
  # GET /sproviders/1.json
  def show
  end

  # GET /sproviders/new
  def new
    @sprovider = Sprovider.new
  end

  # GET /sproviders/1/edit
  def edit
  end

  # POST /sproviders
  # POST /sproviders.json
  def create
    @sprovider = Sprovider.new(sprovider_params)

    respond_to do |format|
      if @sprovider.save
        format.html { redirect_to @sprovider, notice: 'Sprovider was successfully created.' }
        format.json { render :show, status: :created, location: @sprovider }
      else
        format.html { render :new }
        format.json { render json: @sprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sproviders/1
  # PATCH/PUT /sproviders/1.json
  def update
    respond_to do |format|
      if @sprovider.update(sprovider_params)
        format.html { redirect_to @sprovider, notice: 'Sprovider was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprovider }
      else
        format.html { render :edit }
        format.json { render json: @sprovider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sproviders/1
  # DELETE /sproviders/1.json
  def destroy
    @sprovider.destroy
    respond_to do |format|
      format.html { redirect_to sproviders_url, notice: 'Sprovider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprovider
      @sprovider = Sprovider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprovider_params
      params.require(:sprovider).permit(:uname, :doj, :contact_no, :status, :payment, :credit, :date)
    end
end

app/helpers/sproviders_helper.rb
module SprovidersHelper
end

app/views/sproviders/_form.html.erb
<%= form_for(@sprovider) do |f| %>
  <% if @sprovider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprovider.errors.count, "error") %> prohibited this sprovider from being saved:</h2>

      <ul>
      <% @sprovider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %><br>
    <%= f.text_field :uname %>
  </div>
  <div class="field">
    <%= f.label :doj %><br>
    <%= f.date_select :doj %>
  </div>
  <div class="field">
    <%= f.label :contact_no %><br>
    <%= f.number_field :contact_no %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ['Active', 'Inactive'] %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.number_field :payment %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.number_field :credit %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sproviders/edit.html.erb
<h1>Editing Sprovider</h1>

<%= render 'form' %>

<%= link_to 'Show', @sprovider %> |
<%= link_to 'Back', sproviders_path %>

app/views/sproviders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sproviders</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Uname </th>
      <th>Doj </th>
      <th>Contact no</th>
      <th>Status</th>
      <th>Payment</th>
      <th>Credit</th>
      <th>Date</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @sproviders.each do |sprovider| %>
      <tr>
        <td><%= sprovider.uname %></td>
        <td><%= sprovider.doj %></td>
        <td><%= sprovider.contact_no %></td>
        <td><%= sprovider.status %></td>
        <td><%= sprovider.payment %></td>
        <td><%= sprovider.credit %></td>
        <td><%= sprovider.date %></td>
        <td><%= link_to 'Show', sprovider %></td>
        <td><%= link_to 'Edit', edit_sprovider_path(sprovider) %></td>
        <td><%= link_to 'Destroy', sprovider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sprovider', new_sprovider_path %>

app/views/sproviders/new.html.erb
<h1>New Sprovider</h1>

<%= render 'form' %>

<%= link_to 'Back', sproviders_path %>

app/views/sproviders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uname:</strong>
  <%= @sprovider.uname %>
</p>

<p>
  <strong>Doj:</strong>
  <%= @sprovider.doj %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @sprovider.contact_no %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sprovider.status %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @sprovider.payment %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @sprovider.credit %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sprovider.date %>
</p>

<%= link_to 'Edit', edit_sprovider_path(@sprovider) %> |
<%= link_to 'Back', sproviders_path %>