config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get 'customerrequests/index'

  get 'customerrequests/show'

  resources :customers
  resources :sproviders
  
  get '/cooks' => 'cooks#index'
  get 'cooks/:spid' => 'cooks#cookrequest'
  get 'cooks/index'

  get 'cooks/show'

  get 'dataviews/new' => 'dataviews#new'
  devise_scope :user do    
  match '/sessions/user', to: 'devise/sessions#create', via: :post
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'customerrequests/:customer_id' => 'customerrequests#userrequest'
  resources :customerrequests
  resources :dataviews
  resources :cooks
  resources :negative_feedbacks
  root 'dataviews#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.gehelpers.com/">GoEazy Website
    by GE Helpers</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
   
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Operations", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
              <li><%= link_to "Date View", dataviews_path %></li>
              <li><%= link_to "Cooks Stats", cooks_path %></li>
              <li><%= link_to "Customer Stats", customerrequests_path %></li>
              <li><%= link_to "Cooks Details", sproviders_path %></li>
              <li><%= link_to "Negative Feedback", negative_feedbacks_path %></li>
              <li><%= link_to "Costomers", customers_path  %></li>
      
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              
         <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
      
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gorecord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>